"""empty message

Revision ID: 020eed6db219
Revises: 
Create Date: 2020-07-19 15:03:04.219880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020eed6db219'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('zhsz',
    sa.Column('primary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('style_id', sa.String(length=50), nullable=True),
    sa.Column('stu_name', sa.String(length=100), nullable=True),
    sa.Column('political_edu', sa.Float(), nullable=True),
    sa.Column('physical_heal', sa.Float(), nullable=True),
    sa.Column('innovation_entrep', sa.Float(), nullable=True),
    sa.Column('technical_skills', sa.Float(), nullable=True),
    sa.Column('volunte', sa.Float(), nullable=True),
    sa.Column('human_art', sa.Float(), nullable=True),
    sa.Column('zh_theory', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('GPA', sa.Float(), nullable=True),
    sa.Column('zh_score', sa.Float(), nullable=True),
    sa.Column('gk_class', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('year', sa.String(length=50), nullable=True),
    sa.Column('college', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('primary_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zhsz')
    op.drop_table('User')
    # ### end Alembic commands ###
